const { initializeApp, cert } = require('firebase-admin/app');
const { getFirestore } = require('firebase-admin/firestore');

const serviceAccount = require('./sswghtabi-firebase-adminsdk-fbsvc-c4c14f6067.json');

initializeApp({ credential: cert(serviceAccount) });
const db = getFirestore();

// Data Khusus Halaman 74 (Epilog & End)
const page74Data = {
  pageNumber: 74,
  chapter: "第十二章",
  title: "アリスの 証言",
  content: [
    {
      id: "しかし、お姉さんはアリスが去ったあともそのまま静かに座り、手で頭を支え、沈みゆく夕日を眺めながら、小さなアリスとその素晴らしい冒険の数々に思いを馳せていました。やがて彼女自身もどこか夢見心地になり、このような夢を見始めました――",
      paragraphId: "Tetapi kakaknya tetap duduk tenang seperti saat Alice meninggalkannya, menyandarkan頭nya, menyaksikan matahari terbenam, dan memikirkan Alice kecil serta seluruh Petualangan menakjubkannya, sampai dia pun mulai bermimpi dengan caranya sendiri, dan inilah mimpinya:—",
      tokens: [
        { jp: "しかし", reading: "しかし", id: "tetapi" },
        { jp: "、", reading: "", id: "" },
        { jp: "お姉さん", reading: "おねえさん", id: "kakak" },
        { jp: "は", reading: "は", id: "penanda topik" },
        { jp: "アリス", reading: "ありす", id: "Alice" },
        { jp: "が", reading: "が", id: "penanda subjek" },
        { jp: "去った", reading: "さった", id: "meninggalkan" },
        { jp: "あと", reading: "あと", id: "setelah" },
        { jp: "も", reading: "も", id: "pun" },
        { jp: "そのまま", reading: "そのまま", id: "seperti saat itu" },
        { jp: "静かに", reading: "しずかに", id: "tenang" },
        { jp: "座り", reading: "すわり", id: "duduk" },
        { jp: "、", reading: "", id: "" },
        { jp: "手", reading: "て", id: "tangan" },
        { jp: "で", reading: "で", id: "dengan" },
        { jp: "頭", reading: "あたま", id: "kepala" },
        { jp: "を", reading: "を", id: "penanda objek" },
        { jp: "支え", reading: "ささえ", id: "menyandarkan" },
        { jp: "、", reading: "", id: "" },
        { jp: "沈みゆく", reading: "しずみゆく", id: "terbenam" },
        { jp: "夕日", reading: "ゆうひ", id: "matahari terbenam" },
        { jp: "を", reading: "を", id: "penanda objek" },
        { jp: "眺めながら", reading: "ながめながら", id: "sambil menyaksikan" },
        { jp: "、", reading: "", id: "" },
        { jp: "小さな", reading: "ちいさな", id: "kecil" },
        { jp: "アリス", reading: "ありす", id: "Alice" },
        { jp: "と", reading: "と", id: "dan" },
        { jp: "その", reading: "その", id: "itu" },
        { jp: "素晴らしい", reading: "すばらしい", id: "menakjubkan" },
        { jp: "冒険", reading: "ぼうけん", id: "petualangan" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "数々", reading: "かずかず", id: "seluruh / berbagai" },
        { jp: "に", reading: "に", id: "pada" },
        { jp: "思いを馳せていました", reading: "おもいをはせていました", id: "memikirkan" },
        { jp: "。", reading: "", id: "" },
        { jp: "やがて", reading: "やがて", id: "sampai" },
        { jp: "彼女自身", reading: "かのじょじしん", id: "dia sendiri" },
        { jp: "も", reading: "も", id: "pun" },
        { jp: "どこか", reading: "どこか", id: "suatu" },
        { jp: "夢見心地", reading: "ゆめみごこち", id: "bermimpi" },
        { jp: "に", reading: "に", id: "menjadi" },
        { jp: "なり", reading: "なり", id: "mulai" },
        { jp: "、", reading: "", id: "" },
        { jp: "このよう", reading: "このよう", id: "inilah" },
        { jp: "な", reading: "な", id: "adalah" },
        { jp: "夢", reading: "ゆめ", id: "mimpi" },
        { jp: "を", reading: "を", id: "penanda objek" },
        { jp: "見始めました――", reading: "みはじめました", id: "mulai melihat" }
      ]
    },
    {
      id: "まず、彼女は小さなアリス自身の夢を見ました。再びその小さな手が自分の膝の上で重ねられ、生き生きとした輝く瞳が自分を見上げていました。アリスの声の音調、そして目に入りそうになるくせ毛を払うために首をちょんと振るあの愛くるしい仕草までもが見えるようでした。そして耳を傾けていると、周りの場所全体が妹の夢に登場する不思議な生き物たちで生き生きと動き始めました。",
      paragraphId: "Pertama, dia bermimpi tentang Alice kecil sendiri, dan sekali lagi tangan-tangan mungil itu terkatup di atas lututnya, dan mata terang yang antusias menatap ke arah matanya—dia bisa mendengar nada suaranya, dan melihat kibasan kecil kakinya saat mengibaskan rambutnya yang selalu mengganggu matanya—dan saat dia mendengarkan, seluruh tempat di sekitarnya menjadi hidup dengan makhluk-makhluk aneh dari mimpi adik kecilnya.",
      tokens: [
        { jp: "まず", reading: "まず", id: "pertama" },
        { jp: "、", reading: "", id: "" },
        { jp: "彼女", reading: "かのじょ", id: "dia" },
        { jp: "は", reading: "は", id: "penanda topik" },
        { jp: "小さな", reading: "ちいさな", id: "kecil" },
        { jp: "アリス自身", reading: "ありすじしん", id: "Alice sendiri" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "夢", reading: "ゆめ", id: "mimpi" },
        { jp: "を", reading: "を", id: "penanda objek" },
        { jp: "見ました", reading: "みました", id: "melihat" },
        { jp: "。", reading: "", id: "" },
        { jp: "再び", reading: "ふたたび", id: "sekali lagi" },
        { jp: "その", reading: "その", id: "itu" },
        { jp: "小さな", reading: "ちいさな", id: "mungil / kecil" },
        { jp: "手", reading: "て", id: "tangan" },
        { jp: "が", reading: "が", id: "penanda subjek" },
        { jp: "自分", reading: "じぶん", id: "sendiri" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "膝の上", reading: "ひざのうえ", id: "atas lutut" },
        { jp: "で", reading: "で", id: "di" },
        { jp: "重ねられ", reading: "かさねられ", id: "terkatup" },
        { jp: "、", reading: "", id: "" },
        { jp: "生き生きとした", reading: "いきいきとした", id: "hidup / terang" },
        { jp: "輝く", reading: "かがやく", id: "berkilau" },
        { jp: "瞳", reading: "ひとみ", id: "mata" },
        { jp: "が", reading: "が", id: "penanda subjek" },
        { jp: "自分", reading: "じぶん", id: "sendiri" },
        { jp: "を", reading: "を", id: "penanda objek" },
        { jp: "見上げていました", reading: "みあげていました", id: "menatap" },
        { jp: "。", reading: "", id: "" },
        { jp: "アリス", reading: "ありす", id: "Alice" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "声", reading: "こえ", id: "suara" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "音調", reading: "おんちょう", id: "nada" },
        { jp: "、", reading: "", id: "" },
        { jp: "そして", reading: "そして", id: "dan" },
        { jp: "目", reading: "め", id: "mata" },
        { jp: "に", reading: "に", id: "ke" },
        { jp: "入りそうになる", reading: "はいりそうになる", id: "mengganggu" },
        { jp: "くせ毛", reading: "くせげ", id: "rambut" },
        { jp: "を", reading: "を", id: "penanda objek" },
        { jp: "払う", reading: "はらう", id: "mengibaskan" },
        { jp: "ため", reading: "ため", id: "untuk" },
        { jp: "に", reading: "に", id: "pada" },
        { jp: "首", reading: "くび", id: "kepala" },
        { jp: "を", reading: "を", id: "penanda objek" },
        { jp: "ちょんと", reading: "ちょんと", id: "kibasan kecil" },
        { jp: "振る", reading: "ふる", id: "mengibas" },
        { jp: "あの", reading: "あの", id: "itu" },
        { jp: "愛くるしい", reading: "あいくるしい", id: "menggemaskan" },
        { jp: "仕草", reading: "しぐさ", id: "gerakan / kibasan" },
        { jp: "まで", reading: "まで", id: "sampai" },
        { jp: "も", reading: "も", id: "pun" },
        { jp: "が", reading: "が", id: "penanda subjek" },
        { jp: "見える", reading: "みえる", id: "kelihatan" },
        { jp: "ようでした", reading: "ようでした", id: "tampak" },
        { jp: "。", reading: "", id: "" },
        { jp: "そして", reading: "そして", id: "dan" },
        { jp: "耳を傾けていると", reading: "みみをかたむけていると", id: "saat mendengarkan" },
        { jp: "、", reading: "", id: "" },
        { jp: "周り", reading: "まわり", id: "sekitar" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "場所", reading: "ばしょ", id: "tempat" },
        { jp: "全体", reading: "ぜんたい", id: "seluruh" },
        { jp: "が", reading: "が", id: "penanda subjek" },
        { jp: "妹", reading: "いもうと", id: "adik" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "夢", reading: "ゆめ", id: "mimpi" },
        { jp: "に", reading: "に", id: "di" },
        { jp: "登場する", reading: "とうじょうする", id: "muncul" },
        { jp: "不思議な", reading: "ふしぎな", id: "aneh" },
        { jp: "生き物たち", reading: "いきものたち", id: "makhluk-makhluk" },
        { jp: "で", reading: "で", id: "dengan" },
        { jp: "生き生きと", reading: "いきいきと", id: "hidup" },
        { jp: "動き始めました", reading: "うごきはじめました", id: "mulai bergerak" },
        { jp: "。", reading: "", id: "" }
      ]
    },
    {
      id: "白ウサギが急ぎ足で通り過ぎると足元の茂みがガサガサと音を立て、おびえたネズミが近くの池をバシャバシャと泳ぎ渡りました。三月ウサギたちが終わりのないお茶会を楽しむティーカップのカチャカチャという音や、哀れなゲストに処刑を命じる女王の甲高い叫び声が聞こえてきました。公爵夫人の膝の上では豚の赤ん坊がくしゃみをし、皿や鉢が周りでガチャーンと割れ、グリフォンの悲鳴、トカゲの石筆のキーキーという音、鎮圧されるモルモットの詰まった息遣いが、遠くの惨めな代用ウミガメのすすり泣きと混ざり合って空気を満たしました。",
      paragraphId: "Rumput yang panjang berdesir di脚nya saat Kelinci Putih bergegas lewat—Tikus yang ketakutan memercikkan air melintasi kolam di dekatnya—dia bisa mendengar gemerincing cangkir teh saat March Hare dan teman-temannya berbagi makanan yang tak pernah usai, dan suara melengking Ratu yang memerintahkan eksekusi para tamunya yang malang—sekali lagi bayi babi itu bersin di atas lutut Duchess, sementara piring dan mangkuk hancur di sekitarnya—sekali lagi jeritan Gryphon, cicitan pensil batu Kadal, dan rintihan marmut yang ditenangkan, memenuhi udara, bercampur dengan sedu-sedan jauh dari Kura-kura Tiruan yang malang.",
      tokens: [
        { jp: "白ウサギ", reading: "しらうさぎ", id: "Kelinci Putih" },
        { jp: "が", reading: "が", id: "penanda subjek" },
        { jp: "急ぎ足で", reading: "いそぎあしで", id: "bergegas" },
        { jp: "通り過ぎると", reading: "とおりすぎると", id: "lewat" },
        { jp: "足元", reading: "あしもと", id: "kaki" },
        { jp: "の", reading: "の", id: "di" },
        { jp: "茂み", reading: "しげみ", id: "rumput / semak" },
        { jp: "が", reading: "が", id: "penanda subjek" },
        { jp: "ガサガサと", reading: "がさがさと", id: "berdesir" },
        { jp: "音", reading: "おと", id: "suara" },
        { jp: "を", reading: "を", id: "penanda objek" },
        { jp: "立て", reading: "たて", id: "berbunyi" },
        { jp: "、", reading: "", id: "" },
        { jp: "おびえた", reading: "おびえた", id: "ketakutan" },
        { jp: "ネズミ", reading: "ねずみ", id: "Tikus" },
        { jp: "が", reading: "が", id: "penanda subjek" },
        { jp: "近く", reading: "ちかく", id: "dekat" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "池", reading: "いけ", id: "kolam" },
        { jp: "を", reading: "を", id: "penanda objek" },
        { jp: "バシャバシャと", reading: "ばしゃばしゃと", id: "memercikkan air" },
        { jp: "泳ぎ渡りました", reading: "およぎわた理ました", id: "berenang melintasi" },
        { jp: "。", reading: "", id: "" },
        { jp: "三月ウサギたち", reading: "さんがつうさぎたち", id: "March Hare dan temannya" },
        { jp: "が", reading: "が", id: "penanda subjek" },
        { jp: "終わり", reading: "おわり", id: "akhir" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "ない", reading: "ない", id: "tidak ada" },
        { jp: "お茶会", reading: "おちゃかい", id: "makanan / pesta teh" },
        { jp: "を", reading: "を", id: "penanda objek" },
        { jp: "楽しむ", reading: "たのしむ", id: "berbagi / menikmati" },
        { jp: "ティーカップ", reading: "てぃーかっぷ", id: "cangkir teh" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "カチャカチャという", reading: "かちゃかちゃという", id: "gemerincing" },
        { jp: "音", reading: "おと", id: "suara" },
        { jp: "や", reading: "や", id: "dan" },
        { jp: "、", reading: "", id: "" },
        { jp: "哀れな", reading: "あわれな", id: "malang" },
        { jp: "ゲスト", reading: "げすと", id: "tamu" },
        { jp: "に", reading: "に", id: "kepada" },
        { jp: "処刑", reading: "しょけい", id: "eksekusi" },
        { jp: "を", reading: "を", id: "penanda objek" },
        { jp: "命じる", reading: "めいじる", id: "memerintahkan" },
        { jp: "女王", reading: "じょおう", id: "Ratu" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "甲高い", reading: "かんだかい", id: "melengking" },
        { jp: "叫び声", reading: "さけびごえ", id: "suara teriakan" },
        { jp: "が", reading: "が", id: "penanda subjek" },
        { jp: "聞こえてきました", reading: "きこえてきました", id: "terdengar" },
        { jp: "。", reading: "", id: "" },
        { jp: "公爵夫人", reading: "こうしゃくふじん", id: "Duchess" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "膝の上", reading: "ひざのうえ", id: "atas lutut" },
        { jp: "で", reading: "で", id: "di" },
        { jp: "は", reading: "は", id: "penanda topik" },
        { jp: "豚の赤ん坊", reading: "ぶたのあかんぼう", id: "bayi babi" },
        { jp: "が", reading: "が", id: "penanda subjek" },
        { jp: "くしゃみ", reading: "くしゃみ", id: "bersin" },
        { jp: "を", reading: "を", id: "penanda objek" },
        { jp: "し", reading: "し", id: "melakukan" },
        { jp: "、", reading: "", id: "" },
        { jp: "皿", reading: "さら", id: "piring" },
        { jp: "や", reading: "や", id: "dan" },
        { jp: "鉢", reading: "はち", id: "mangkuk" },
        { jp: "が", reading: "が", id: "penanda subjek" },
        { jp: "周り", reading: "まわり", id: "sekitar" },
        { jp: "で", reading: "で", id: "di" },
        { jp: "ガチャーンと", reading: "がちゃーんと", id: "hancur" },
        { jp: "割れ", reading: "われ", id: "pecah" },
        { jp: "、", reading: "", id: "" },
        { jp: "グリフォン", reading: "ぐりふぉん", id: "Gryphon" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "悲鳴", reading: "ひめい", id: "jeritan" },
        { jp: "、", reading: "", id: "" },
        { jp: "トカゲ", reading: "とかげ", id: "Kadal" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "石筆", reading: "せきひつ", id: "pensil batu" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "キーキーという", reading: "きーきーという", id: "cicitan" },
        { jp: "音", reading: "おと", id: "suara" },
        { jp: "、", reading: "", id: "" },
        { jp: "鎮圧される", reading: "ちんあつされる", id: "ditenangkan" },
        { jp: "モルモット", reading: "もるもっと", id: "marmut" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "詰まった", reading: "つまった", id: "rintihan" },
        { jp: "息遣い", reading: "いきづかい", id: "desah napas" },
        { jp: "が", reading: "が", id: "penanda subjek" },
        { jp: "、", reading: "", id: "" },
        { jp: "遠く", reading: "とおく", id: "jauh" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "惨めな", reading: "みじめな", id: "malang" },
        { jp: "代用ウミガメ", reading: "だいよううみがめ", id: "Kura-kura Tiruan" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "すすり泣き", reading: "すすりなき", id: "sedu-sedan" },
        { jp: "と", reading: "と", id: "dengan" },
        { jp: "混ざり合って", reading: "まざりあって", id: "bercampur" },
        { jp: "空気", reading: "くうき", id: "udara" },
        { jp: "を", reading: "を", id: "penanda objek" },
        { jp: "満たしました", reading: "みたしました", id: "memenuhi" },
        { jp: "。", reading: "", id: "" }
      ]
    },
    {
      id: "そうして彼女は目を閉じたまま座り続け、自分自身が不思議の国にいるのだと半ば信じ込みました。目を開ければ全てが退屈な現実に変わってしまうと分かってはいながらも――草は風になびくだけとなり、池の波立ちは揺れる葦の音に、カチャカチャ鳴るティーカップは羊の鈴の音に、女王の甲高い叫び声は羊飼いの少年のにぎやかな声に変わってしまうのです。そして赤ん坊のくしゃみも、グリフォンの悲鳴も、その他のあらゆる奇妙な音も、忙しい農場のガヤガヤとした騒音に変わり、遠くの牛の鳴き声が代用ウミガメの重いすすり泣きに取って代わるのだと知りながらも。",
      paragraphId: "Jadi dia terus duduk dengan mata terpejam, dan separuh percaya dirinya berada di Wonderland, meskipun dia tahu dia hanya perlu membukanya lagi, dan semuanya akan berubah menjadi kenyataan yang membosankan—rumput hanya akan berdesir tertiup angin, dan kolam bergelombang oleh lambaian alang-alang—cangkir teh yang gemerincing akan berubah menjadi dentang lonceng domba, dan teriakan melengking Ratu menjadi suara anak gembala—dan bersin bayi, jeritan Gryphon, dan semua suara aneh lainnya, akan berubah (dia tahu) menjadi hiruk-pikuk halaman pertanian yang sibuk—sementara lenguhan sapi di kejauhan akan menggantikan sedu-sedan Kura-kura Tiruan.",
      tokens: [
        { jp: "そうして", reading: "そうして", id: "jadi" },
        { jp: "彼女", reading: "かのじょ", id: "dia" },
        { jp: "は", reading: "は", id: "penanda topik" },
        { jp: "目", reading: "め", id: "mata" },
        { jp: "を", reading: "を", id: "penanda objek" },
        { jp: "閉じ", reading: "とじ", id: "terpejam" },
        { jp: "た", reading: "た", id: "yang" },
        { jp: "まま", reading: "まま", id: "dengan" },
        { jp: "座り続け", reading: "すわりつづけ", id: "duduk" },
        { jp: "、", reading: "", id: "" },
        { jp: "自分自身", reading: "じぶんじしん", id: "dirinya" },
        { jp: "が", reading: "が", id: "penanda subjek" },
        { jp: "不思議の国", reading: "ふしぎのくに", id: "Wonderland" },
        { jp: "に", reading: "に", id: "di" },
        { jp: "いる", reading: "いる", id: "berada" },
        { jp: "の", reading: "の", id: "hal" },
        { jp: "だ", reading: "だ", id: "adalah" },
        { jp: "と", reading: "と", id: "bahwa" },
        { jp: "半ば", reading: "なかば", id: "separuh" },
        { jp: "信じ込みました", reading: "しんじこみました", id: "percaya" },
        { jp: "。", reading: "", id: "" },
        { jp: "目", reading: "め", id: "mata" },
        { jp: "を", reading: "を", id: "penanda objek" },
        { jp: "開ければ", reading: "あければ", id: "membukanya" },
        { jp: "全て", reading: "すべて", id: "semuanya" },
        { jp: "が", reading: "が", id: "penanda subjek" },
        { jp: "退屈な", reading: "たいくつな", id: "membosankan" },
        { jp: "現実", reading: "げんじつ", id: "kenyataan" },
        { jp: "に", reading: "に", id: "menjadi" },
        { jp: "変わってしまう", reading: "かわってしまう", id: "akan berubah" },
        { jp: "と", reading: "と", id: "bahwa" },
        { jp: "分かってはいながらも", reading: "わかってはいながらも", id: "meskipun tahu" },
        { jp: "――", reading: "", id: "" },
        { jp: "草", reading: "くさ", id: "rumput" },
        { jp: "は", reading: "は", id: "penanda topik" },
        { jp: "風", reading: "かぜ", id: "angin" },
        { jp: "に", reading: "に", id: "oleh" },
        { jp: "なびくだけ", reading: "なびくだけ", id: "berdesir" },
        { jp: "と", reading: "と", id: "menjadi" },
        { jp: "なり", reading: "なり", id: "menjadi" },
        { jp: "、", reading: "", id: "" },
        { jp: "池", reading: "いけ", id: "kolam" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "波立ち", reading: "なみだち", id: "gelombang" },
        { jp: "は", reading: "は", id: "penanda topik" },
        { jp: "揺れる", reading: "ゆれる", id: "lambaian" },
        { jp: "葦", reading: "あし", id: "alang-alang" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "音", reading: "おと", id: "suara" },
        { jp: "に", reading: "に", id: "menjadi" },
        { jp: "、", reading: "", id: "" },
        { jp: "カチャカチャ", reading: "かちゃかちゃ", id: "gemerincing" },
        { jp: "鳴る", reading: "なる", id: "bunyi" },
        { jp: "ティーカップ", reading: "てぃーかっぷ", id: "cangkir teh" },
        { jp: "は", reading: "は", id: "penanda topik" },
        { jp: "羊", reading: "ひつじ", id: "domba" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "鈴の音", reading: "すずのおと", id: "lonceng" },
        { jp: "に", reading: "に", id: "menjadi" },
        { jp: "、", reading: "", id: "" },
        { jp: "女王", reading: "じょおう", id: "Ratu" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "甲高い", reading: "かんだかい", id: "melengking" },
        { jp: "叫び声", reading: "さけびごえ", id: "teriakan" },
        { jp: "は", reading: "は", id: "penanda topik" },
        { jp: "羊飼い", reading: "ひつじかい", id: "gembala" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "少年", reading: "しょうねん", id: "anak" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "にぎやかな", reading: "にぎやかな", id: "suara" },
        { jp: "声", reading: "こえ", id: "suara" },
        { jp: "に", reading: "に", id: "menjadi" },
        { jp: "変わってしまうの", reading: "かわってしまうの", id: "akan berubah" },
        { jp: "です", reading: "です", id: "adalah" },
        { jp: "。", reading: "", id: "" },
        { jp: "そして", reading: "そして", id: "dan" },
        { jp: "赤ん坊", reading: "あかんぼう", id: "bayi" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "くしゃみ", reading: "くしゃみ", id: "bersin" },
        { jp: "も", reading: "も", id: "pun" },
        { jp: "、", reading: "", id: "" },
        { jp: "グリフォン", reading: "ぐりふぉん", id: "Gryphon" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "悲鳴", reading: "ひめい", id: "jeritan" },
        { jp: "も", reading: "も", id: "pun" },
        { jp: "、", reading: "", id: "" },
        { jp: "その他", reading: "そのた", id: "lainnya" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "あらゆる", reading: "あらゆる", id: "semua" },
        { jp: "奇妙な", reading: "きみょうな", id: "aneh" },
        { jp: "音", reading: "おと", id: "suara" },
        { jp: "も", reading: "も", id: "pun" },
        { jp: "、", reading: "", id: "" },
        { jp: "忙しい", reading: "いそがしい", id: "sibuk" },
        { jp: "農場", reading: "のうじょう", id: "halaman pertanian" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "ガヤガヤとした", reading: "がやがやとした", id: "hiruk-pikuk" },
        { jp: "騒音", reading: "そうおん", id: "kebisingan" },
        { jp: "に", reading: "に", id: "menjadi" },
        { jp: "変わり", reading: "かわり", id: "berubah" },
        { jp: "、", reading: "", id: "" },
        { jp: "遠く", reading: "とおく", id: "kejauhan" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "牛", reading: "うし", id: "sapi" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "鳴き声", reading: "なきごえ", id: "lenguhan" },
        { jp: "が", reading: "が", id: "penanda subjek" },
        { jp: "代用ウミガメ", reading: "だいよううみがめ", id: "Kura-kura Tiruan" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "重い", reading: "おもい", id: "berat" },
        { jp: "すすり泣き", reading: "すすりなき", id: "sedu-sedan" },
        { jp: "に", reading: "に", id: "menggantikan" },
        { jp: "取って代わる", reading: "とって代わる", id: "menggantikan" },
        { jp: "のだ", reading: "のだ", id: "hal" },
        { jp: "と", reading: "と", id: "bahwa" },
        { jp: "知りながらも", reading: "しりながらも", id: "meskipun tahu" },
        { jp: "。", reading: "", id: "" }
      ]
    },
    {
      id: "最後に、彼女は思い描きました。この小さな妹がやがて成長して大人の女性になり、どれほど歳を重ねても、幼少期の純粋で愛に満ちた心を保ち続ける姿を。そして自分の周りに他の小さな子供たちを集め、数々の不思議なお話や、もしかするとずっと昔の「不思議の国」の夢を語り聞かせて、子供たちの目を輝かせ、夢中にさせる姿を。そして子供たちの素朴な悲しみに心から寄り添い、素朴な喜びに喜びを見出し、自分自身の幼い頃の生活と、あの幸せな夏の zikan（日々）を思い返す姿を――\n\n◆ ◇ ◆  完  ◆ ◇ ◆\n（ Alice's Adventures in Wonderland - THE END ）",
      paragraphId: "Terakhir, dia membayangkan bagaimana adik kecilnya ini kelak, di masa depan, akan menjadi seorang wanita dewasa; dan bagaimana dia akan menjaga, sepanjang usianya yang makin matang, hati masa kecilnya yang polos dan penuh kasih: dan bagaimana dia akan mengumpulkan anak-anak kecil lain di sekitarnya, dan membuat mata mereka berbinar dan antusias dengan banyak cerita aneh, bahkan mungkin dengan mimpi Wonderland zaman dulu: dan bagaimana dia akan merasakan semua kesedihan sederhana mereka, dan menemukan kebahagiaan dalam semua kegembiraan sederhana mereka, mengingat masa kecilnya sendiri, dan hari-hari musim panas yang bahagia.\n\n◆ ◇ ◆  TAMAT  ◆ ◇ ◆\n（ Petualangan Alice di Negeri Ajaib - THE END ）",
      tokens: [
        { jp: "最後", reading: "さいご", id: "terakhir" },
        { jp: "に", reading: "に", id: "pada" },
        { jp: "、", reading: "", id: "" },
        { jp: "彼女", reading: "かのじょ", id: "dia" },
        { jp: "は", reading: "は", id: "penanda topik" },
        { jp: "思い描きました", reading: "おもいえがきました", id: "membayangkan" },
        { jp: "。", reading: "", id: "" },
        { jp: "この", reading: "この", id: "ini" },
        { jp: "小さな", reading: "ちいさな", id: "kecil" },
        { jp: "妹", reading: "いもうと", id: "adik" },
        { jp: "が", reading: "が", id: "penanda subjek" },
        { jp: "やがて", reading: "やがて", id: "kelak" },
        { jp: "成長して", reading: "せいちょうして", id: "menjadi dewasa" },
        { jp: "大人", reading: "おとな", id: "dewasa" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "女性", reading: "じょせい", id: "wanita" },
        { jp: "に", reading: "に", id: "menjadi" },
        { jp: "なり", reading: "なり", id: "menjadi" },
        { jp: "、", reading: "", id: "" },
        { jp: "どれほど", reading: "どれほど", id: "sepanjang" },
        { jp: "歳を重ねても", reading: "としをかさねても", id: "makin matang" },
        { jp: "、", reading: "", id: "" },
        { jp: "幼少期", reading: "ようしょうき", id: "masa kecil" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "純粋", reading: "じゅんすい", id: "polos" },
        { jp: "で", reading: "で", id: "dan" },
        { jp: "愛", reading: "あい", id: "kasih" },
        { jp: "に", reading: "に", id: "penuh" },
        { jp: "満ちた", reading: "みちた", id: "penuh" },
        { jp: "心", reading: "こころ", id: "hati" },
        { jp: "を", reading: "を", id: "penanda objek" },
        { jp: "保ち続ける", reading: "たもちつづける", id: "menjaga" },
        { jp: "姿", reading: "すがた", id: "sosok / cara" },
        { jp: "を", reading: "を", id: "penanda objek" },
        { jp: "。", reading: "", id: "" },
        { jp: "そして", reading: "そして", id: "dan" },
        { jp: "自分", reading: "じぶん", id: "sendiri" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "周り", reading: "まわり", id: "sekitar" },
        { jp: "に", reading: "に", id: "di" },
        { jp: "他", reading: "ほか", id: "lain" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "小さな", reading: "ちいさな", id: "kecil" },
        { jp: "子供たち", reading: "こどもたち", id: "anak-anak" },
        { jp: "を", reading: "を", id: "penanda objek" },
        { jp: "集め", reading: "あつめ", id: "mengumpulkan" },
        { jp: "、", reading: "", id: "" },
        { jp: "数々", reading: "かずかず", id: "banyak" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "不思議な", reading: "ふしぎな", id: "aneh" },
        { jp: "お話", reading: "おはなし", id: "cerita" },
        { jp: "や", reading: "や", id: "atau" },
        { jp: "、", reading: "", id: "" },
        { jp: "もしかすると", reading: "もしかすると", id: "mungkin" },
        { jp: "ずっと", reading: "ずっと", id: "zaman" },
        { jp: "昔", reading: "むかし", id: "dulu" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "「不思議の国」", reading: "ふしぎのくに", id: "Wonderland" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "夢", reading: "ゆめ", id: "mimpi" },
        { jp: "を", reading: "を", id: "penanda objek" },
        { jp: "語り聞かせて", reading: "かたりきかせて", id: "bercerita" },
        { jp: "、", reading: "", id: "" },
        { jp: "子供たち", reading: "こどもたち", id: "anak-anak" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "目", reading: "め", id: "mata" },
        { jp: "を", reading: "を", id: "penanda objek" },
        { jp: "輝かせ", reading: "かがやかせ", id: "berbinar" },
        { jp: "、", reading: "", id: "" },
        { jp: "夢中", reading: "むちゅう", id: "antusias" },
        { jp: "に", reading: "に", id: "membuat" },
        { jp: "させる", reading: "させる", id: "membuat" },
        { jp: "姿", reading: "すがた", id: "sosok" },
        { jp: "を", reading: "を", id: "penanda objek" },
        { jp: "。", reading: "", id: "" },
        { jp: "そして", reading: "そして", id: "dan" },
        { jp: "子供たち", reading: "こどもたち", id: "anak-anak" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "素朴な", reading: "そぼくな", id: "sederhana" },
        { jp: "悲しみ", reading: "かなしみ", id: "kesedihan" },
        { jp: "に", reading: "に", id: "pada" },
        { jp: "心から", reading: "こころから", id: "dengan hati" },
        { jp: "寄り添い", reading: "よりそい", id: "merasakan" },
        { jp: "、", reading: "", id: "" },
        { jp: "素朴な", reading: "そぼくな", id: "sederhana" },
        { jp: "喜び", reading: "よろこび", id: "kegembiraan" },
        { jp: "に", reading: "に", id: "dalam" },
        { jp: "喜び", reading: "よろこび", id: "kebahagiaan" },
        { jp: "を", reading: "を", id: "penanda objek" },
        { jp: "見出し", reading: "みだし", id: "menemukan" },
        { jp: "、", reading: "", id: "" },
        { jp: "自分自身", reading: "じぶんじしん", id: "sendiri" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "幼い", reading: "おさない", id: "kecil" },
        { jp: "頃", reading: "ころ", id: "masa" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "生活", reading: "せいかつ", id: "kehidupan" },
        { jp: "と", reading: "と", id: "dan" },
        { jp: "、", reading: "", id: "" },
        { jp: "あの", reading: "あの", id: "itu" },
        { jp: "幸せな", reading: "しあわせな", id: "bahagia" },
        { jp: "夏", reading: "なつ", id: "musim panas" },
        { jp: "の", reading: "の", id: "dari" },
        { jp: "日々", reading: "ひび", id: "hari-hari" },
        { jp: "を", reading: "を", id: "penanda objek" },
        { jp: "思い返す", reading: "おもいかえす", id: "mengingat" },
        { jp: "姿", reading: "すがた", id: "sosok" },
        { jp: "を――", reading: "を", id: "penanda objek" },
        { jp: "◆ ◇ ◆  完  ◆ ◇ ◆", reading: "かん", id: "tamat" }
      ]
    }
  ]
};

async function uploadPage74ToSubcollection() {
  try {
    const formattedPageId = `page_${String(page74Data.pageNumber).padStart(3, '0')}`;

    const pageRef = db
      .collection('immersion_novels')
      .doc('alice_adventures_in_wonderland')
      .collection('pages')
      .doc(formattedPageId);

    await pageRef.set(page74Data);

    console.log(`🎉 Halaman Epilog Terakhir (Page ${page74Data.pageNumber}) berhasil diunggah dengan ID: ${formattedPageId}`);
    console.log(`✨ Seluruh isi novel "Alice's Adventures in Wonderland" telah Selesai Diunggah secara Lengkap! ✨`);
  } catch (error) {
    console.error(`❌ Gagal mengunggah Halaman ${page74Data.pageNumber}:`, error);
  }
}

uploadPage74ToSubcollection();